# Generated by Django 2.2.7 on 2020-02-08 07:29

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200107_0520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
