# Generated by Django 2.2.7 on 2020-02-12 09:49

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20200209_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='콤마를 기준으로 태그가 설정됩니다!', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
