# Generated by Django 2.2.7 on 2020-02-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default="{% static 'images/basic.png' %}", upload_to='img/', verbose_name='Image of User'),
        ),
    ]
